# Generated by Django 4.0.5 on 2022-09-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0002_files_name_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
    ]
