# Generated by Django 4.0.5 on 2022-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0003_remove_files_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='defualt', max_length=255),
        ),
    ]
