# Generated by Django 4.0.5 on 2022-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0006_files_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='key',
            field=models.FileField(upload_to=''),
        ),
    ]
