# Generated by Django 4.0.5 on 2022-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0007_alter_files_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='key',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
