# Generated by Django 4.0.5 on 2022-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0008_alter_files_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(default='defualt', max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='Encryption',
        ),
    ]
