# Generated by Django 4.0.5 on 2022-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapp', '0011_alter_decryption_file_alter_encryption_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compressed')),
                ('name', models.CharField(default='defualt', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Decompressed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='decompressed')),
                ('name', models.CharField(default='defualt', max_length=255)),
            ],
        ),
    ]
